
import NavSideBarLayout from '@/components/Layouts/NavSideBarLayout';
import 'bootstrap/dist/css/bootstrap.min.css';
import "leaflet/dist/leaflet.css";
import Script from 'next/script';
import './globals.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html>
      <body>
        <div className='w-100'>
          {/* <!-- partial:partials/_navbar.html --> */}
          <NavSideBarLayout>
            {children}
          </NavSideBarLayout>
          {/* <!-- page-body-wrapper ends --> */}
        </div>
        {/* <!-- container-scroller --> */}
        {/* <!-- plugins:js --> */}
        <Script src="/js/jquery.js" strategy="afterInteractive" />
        <Script src="/js/vendor.bundle.base.js" strategy="afterInteractive" />
        {/* <!-- endinject --> */}
        <Script src="/js/template.js" strategy="afterInteractive" />

      </body>
    </html>
  )
}
